####################################################################################################
## FileName:             checkout-sources.yml
## Copyright:            Copyright © 2017-2019 Thomas Corwin, et al. All Rights Reserved.
## License:              https://github.com/tom-corwin/tcdfx/blob/master/LICENSE.md
####################################################################################################

steps:


- checkout: self
  clean: true
  